name: Package Release Next Dev Iteration
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: 1.0.0
        required: true
  
jobs:
  docker-build:
    runs-on: ubuntu-latest
    environment: docker-maven-ghactions-release
    steps:
    - uses: actions/checkout@v1
      with:
        ref: main
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Configure Settings XML
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        output_file: foo/settings.xml
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/smilebat96/Releases", "snapshots": {"enabled": "true"} }]'
        servers: '[{ "id": "github", "username": "smilebat96", "password": "${{ secrets.MY_GITHUB_TOKEN }}" }]'
    - name: Configure git
      run: |
        git config --global committer.email "noreply@github.com"
        git config --global committer.name "GitHub"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"
    - name: Checkout main branch
      run: git checkout main
    - name: Prepare release
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        mvn -B --file pom.xml --settings foo/settings.xml clean install -Pskip_static
        mvn -B release:prepare --settings foo/settings.xml -DignoreSnapshots=true -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN -Darguments=" -Dmaven.javadoc.skip=true -P docker-deploy"
    - name: Perform release
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: mvn -B release:perform --settings foo/settings.xml -DignoreSnapshots=true -Darguments="-Dmaven.javadoc.skip=true -P docker-deploy -Ddocker.token=$DOCKER_HUB_TOKEN"
